name: cloud-ide-workspace
region: nyc
services:
- name: web-ide
  dockerfile_path: Dockerfile
  source_dir: /
  envs:
  - key: PASSWORD
    value: your-secure-password
    type: SECRET
  - key: CLAUDE_API_KEY
    value: your-claude-api-key
    type: SECRET
  - key: OPENAI_API_KEY
    value: your-openai-api-key
    type: SECRET
  - key: GEMINI_API_KEY
    value: your-gemini-api-key
    type: SECRET
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-2gb
  routes:
  - path: /